In [1]:
import os
import pandas as pd

In [2]:
DATASET_PATH = "dataset"

In [3]:
df = pd.read_csv(os.path.join(DATASET_PATH, "7k dataset.txt"))
df

,TENURE,AGE,GENDER,NATIONALITY,STATE,STATUS_BEFORE,STATUS_AFTER,OFFER_TAKER,OFFER_TAKE_UP_DT,DATA_PURC_BEFORE,...,RLD_IND_BEFORE,RLD_IND_AFTER,RLD_AMT_BEFORE,RLD_AMT_AFTER,CPA_RVN_BEFORE,CPA_RVN_AFTER,ARPU_BEFORE,ARPU_AFTER,ACTVIITY_DAYS_AFTER,ACTIVITY_STATUS_AFTER
0,133,33,Male,Malaysia,KLANG VALLEY,Active,Active,Y,10/6/2022,Y,...,Y,Y,30.00,30.00,?,?,26.000000,17.000000,2,DURING & AFTER CAMP
1,37,41,Male,Malaysia,SARAWAK,Active,Active,Y,10/6/2022,Y,...,N,N,?,?,?,?,?,?,37,NO ACTIVITY SINCE SEP
2,44,21,Male,Malaysia,SARAWAK,Active,Active,N,?,N,...,N,N,?,?,?,?,?,?,38,NO ACTIVITY SINCE SEP
3,176,69,Female,Malaysia,PENANG,Active,Active,N,?,N,...,N,N,?,?,?,?,?,?,37,NO ACTIVITY SINCE SEP
4,171,79,Male,Malaysia,JOHORE,Active,Active,Y,10/6/2022,N,...,N,N,?,?,?,?,?,?,5,DURING & AFTER CAMP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7267,28,27,Male,Malaysia,KLANG VALLEY,Active,Active,Y,10/6/2022,Y,...,N,N,?,?,?,?,?,?,0,DURING & AFTER CAMP
7268,48,25,Male,Malaysia,KLANG VALLEY,Active,Active,Y,10/8/2022,Y,...,Y,N,5.00,?,0.15,?,8.730000,3.120000,0,DURING & AFTER CAMP
7269,71,65,Male,Malaysia,PAHANG,Active,Active,Y,10/6/2022,Y,...,N,Y,?,40.00,?,?,29.980000,40.000000,0,DURING & AFTER CAMP
7270,30,33,Male,Malaysia,JOHORE,Active,Active,N,?,N,...,Y,N,20.00,?,?,?,17.000000,?,36,NO ACTIVITY SINCE SEP
7271,16,36,Female,Malaysia,KLANG VALLEY,Active,Active,Y,10/6/2022,Y,...,N,N,?,?,?,?,?,?,0,DURING & AFTER CAMP

## Requirements for midterms
1. Dataset has enough attributes for star schema drill down and roll up.
2. Random values generated for newly added attributes.
3. Resulting dataset is 10% of the original dataset, sampled randomly.

### Existing attributes
| Variable | Description |
| --- | --- | 
| ID | Customer ID
| TENURE | Customer duration with Kation since registration date 
| AGE | Customer age 
| GENDER | Customer gender 
| NATIONALITY | Customer nationality 
| STATE | Customer hometown (state) 
| STATUS_BEFORE | Customer status before campaign launched. 
| STATUS_AFTER | Customer status after campaign ended. 
| OFFER_TAKER | Indicator for customers who opted-in the migration plan. 
| OFFER_TAKE_UP_DT | Date for customers who opted-in the migration plan. 
| DATA_PURC_BEFORE | Indicator for customer who purchased data before campaign launched. 
| DATA_PURC_AFTER | Indicator for customer who purchased data after campaign ended. 
| DATA_CHRG_BEFORE | Total amount of data charged before campaign launched. 
| DATA_CHRG_AFTER | Total amount of data charged after campaign ended. 
| DATA_USG_BEFORE | Data usage before campaign launched. 
| DATA_USG_AFTER | Data usage after campaign ended. 
| VOICE_USG_BEFORE | Voice usage before campaign launched. 
| VOICE_USG_AFTER | Voice usage after campaign ended. 
| RLD_IND_BEFORE | Indicator for customer who reload before campaign launched. 
| RLD_IND_AFTER | Indicator for customer who reload after campaign ended. 
| RLD_AMT_BEFORE | Total of reload amount before campaign launched. 
| RLD_AMT_AFTER | Total of reload amount after campaign ended. 
| ARPU_BEFORE | ARPU before campaign launched. 
| CPA_RVN_BEFORE | Total added value service before campaign launched. 
| CPA_RVN_AFTER | Total added value service after campaign ended. 
| ARPU_AFTER | ARPU after campaign ended. 
| ACTIVITY_DAYS_AFTER | Silent days after campaign ended. 
| ACTIVITY_STATUS_AFTER | Customer activity status after campaign ended. 

### Proposed new attributes
| Variable | Description |
| --- | --- | 
| PLAN_ID | Telco plan ID
| PLAN_TYPE | Name of telco plan

### Values for new attributes
| PLAN_ID | PLAN_TYPE |
| --- | --- | 
| 1 | Saver
| 2 | Premium

![Star schema](media/star_schema.jpg)

## Create new attributes

New attributes `PLAN_ID` and `PLAN_TYPE` will be created and their values are created randomly.

In [4]:
import random

plan_id = range(1, 2 + 1)
plan_ids = random.choices(plan_id, k=len(df))
len(plan_ids)

7272

In [5]:
df["PLAN_ID"] = plan_ids
df

,TENURE,AGE,GENDER,NATIONALITY,STATE,STATUS_BEFORE,STATUS_AFTER,OFFER_TAKER,OFFER_TAKE_UP_DT,DATA_PURC_BEFORE,...,RLD_IND_AFTER,RLD_AMT_BEFORE,RLD_AMT_AFTER,CPA_RVN_BEFORE,CPA_RVN_AFTER,ARPU_BEFORE,ARPU_AFTER,ACTVIITY_DAYS_AFTER,ACTIVITY_STATUS_AFTER,PLAN_ID
0,133,33,Male,Malaysia,KLANG VALLEY,Active,Active,Y,10/6/2022,Y,...,Y,30.00,30.00,?,?,26.000000,17.000000,2,DURING & AFTER CAMP,1
1,37,41,Male,Malaysia,SARAWAK,Active,Active,Y,10/6/2022,Y,...,N,?,?,?,?,?,?,37,NO ACTIVITY SINCE SEP,2
2,44,21,Male,Malaysia,SARAWAK,Active,Active,N,?,N,...,N,?,?,?,?,?,?,38,NO ACTIVITY SINCE SEP,1
3,176,69,Female,Malaysia,PENANG,Active,Active,N,?,N,...,N,?,?,?,?,?,?,37,NO ACTIVITY SINCE SEP,1
4,171,79,Male,Malaysia,JOHORE,Active,Active,Y,10/6/2022,N,...,N,?,?,?,?,?,?,5,DURING & AFTER CAMP,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7267,28,27,Male,Malaysia,KLANG VALLEY,Active,Active,Y,10/6/2022,Y,...,N,?,?,?,?,?,?,0,DURING & AFTER CAMP,1
7268,48,25,Male,Malaysia,KLANG VALLEY,Active,Active,Y,10/8/2022,Y,...,N,5.00,?,0.15,?,8.730000,3.120000,0,DURING & AFTER CAMP,2
7269,71,65,Male,Malaysia,PAHANG,Active,Active,Y,10/6/2022,Y,...,Y,?,40.00,?,?,29.980000,40.000000,0,DURING & AFTER CAMP,2
7270,30,33,Male,Malaysia,JOHORE,Active,Active,N,?,N,...,N,20.00,?,?,?,17.000000,?,36,NO ACTIVITY SINCE SEP,2
7271,16,36,Female,Malaysia,KLANG VALLEY,Active,Active,Y,10/6/2022,Y,...,N,?,?,?,?,?,?,0,DURING & AFTER CAMP,1

In [7]:
plans = {1: "Saver", 2: "Premium"}

df["PLAN_TYPE"] = df["PLAN_ID"].apply(lambda x: plans.get(x))
df

,TENURE,AGE,GENDER,NATIONALITY,STATE,STATUS_BEFORE,STATUS_AFTER,OFFER_TAKER,OFFER_TAKE_UP_DT,DATA_PURC_BEFORE,...,RLD_AMT_BEFORE,RLD_AMT_AFTER,CPA_RVN_BEFORE,CPA_RVN_AFTER,ARPU_BEFORE,ARPU_AFTER,ACTVIITY_DAYS_AFTER,ACTIVITY_STATUS_AFTER,PLAN_ID,PLAN_TYPE
0,133,33,Male,Malaysia,KLANG VALLEY,Active,Active,Y,10/6/2022,Y,...,30.00,30.00,?,?,26.000000,17.000000,2,DURING & AFTER CAMP,1,Saver
1,37,41,Male,Malaysia,SARAWAK,Active,Active,Y,10/6/2022,Y,...,?,?,?,?,?,?,37,NO ACTIVITY SINCE SEP,2,Premium
2,44,21,Male,Malaysia,SARAWAK,Active,Active,N,?,N,...,?,?,?,?,?,?,38,NO ACTIVITY SINCE SEP,1,Saver
3,176,69,Female,Malaysia,PENANG,Active,Active,N,?,N,...,?,?,?,?,?,?,37,NO ACTIVITY SINCE SEP,1,Saver
4,171,79,Male,Malaysia,JOHORE,Active,Active,Y,10/6/2022,N,...,?,?,?,?,?,?,5,DURING & AFTER CAMP,1,Saver
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7267,28,27,Male,Malaysia,KLANG VALLEY,Active,Active,Y,10/6/2022,Y,...,?,?,?,?,?,?,0,DURING & AFTER CAMP,1,Saver
7268,48,25,Male,Malaysia,KLANG VALLEY,Active,Active,Y,10/8/2022,Y,...,5.00,?,0.15,?,8.730000,3.120000,0,DURING & AFTER CAMP,2,Premium
7269,71,65,Male,Malaysia,PAHANG,Active,Active,Y,10/6/2022,Y,...,?,40.00,?,?,29.980000,40.000000,0,DURING & AFTER CAMP,2,Premium
7270,30,33,Male,Malaysia,JOHORE,Active,Active,N,?,N,...,20.00,?,?,?,17.000000,?,36,NO ACTIVITY SINCE SEP,2,Premium
7271,16,36,Female,Malaysia,KLANG VALLEY,Active,Active,Y,10/6/2022,Y,...,?,?,?,?,?,?,0,DURING & AFTER CAMP,1,Saver

In [8]:
df[:round(len(df) * 0.1)].to_csv("midterm_dataset.csv")